config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#index'

  mount RailsAdmin::Engine => '/cms', as: 'rails_admin'
  resources :images
  resources :charges
  devise_for :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
class Image < ApplicationRecord
  has_many :pictures, dependent: :destroy, inverse_of: :image
  has_many :users, through: :pictures

  validates_presence_of :name, :tags, :photo, :price, :users

  # This method associates the attribute ":photo" with a file attachment
  has_attached_file :photo, styles: {
    thumb: '100x100>',
    square: '200x200#',
    medium: '300x300>'
  }

  # Validate the attached image is image/jpg, image/png, etc
  validates_attachment_content_type :photo, :content_type => /\Aimage\/.*\Z/

  scope :to_shop,
    -> (user) { joins(:pictures).
                where("pictures.user_id != ?", user.id).
                where("pictures.image_id not in (?)", user.images.ids) }

  scope :my_images,
    -> (user) { joins(:pictures).
                where("pictures.user_id = ?", user.id) }
end

app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :user
  belongs_to :image

  validates_presence_of :user, :image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :pictures, dependent: :destroy, inverse_of: :user
  has_many :images, through: :pictures
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
    @image = Image.find_by(id: charge_params[:image_id])
  end

  def create
    image = Image.find_by(id: charge_params[:image_id])
    @amount = image.price

    if image.price != charge_params[:price].to_f
      raise "The price does not match, please check and do it again"
    end

    customer = Stripe::Customer.create(
      :email => params[:stripeEmail],
      :source  => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => image.price,
      :description => 'Rails Stripe customer',
      :currency    => 'usd'
    )

    Picture.create user_id: current_user.id, image_id: image.id

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end

  private
    def charge_params
      params.permit(:stripeToken, :stripeEmail, :image_id, :price)
    end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: [:show, :edit, :update, :destroy]

  # GET /images
  # GET /images.json
  def index
    @images = Image.all
  end

  # GET /images/1
  # GET /images/1.json
  def show
  end

  # GET /images/new
  def new
    @image = Image.new
  end

  # GET /images/1/edit
  def edit
  end

  # POST /images
  # POST /images.json
  def create
    @image = Image.new(image_params)

    respond_to do |format|
      if @image.save
        format.html { redirect_to @image, notice: 'Image was successfully created.' }
        format.json { render :show, status: :created, location: @image }
      else
        format.html { render :new }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /images/1
  # PATCH/PUT /images/1.json
  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to @image, notice: 'Image was successfully updated.' }
        format.json { render :show, status: :ok, location: @image }
      else
        format.html { render :edit }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @image.destroy
    respond_to do |format|
      format.html { redirect_to images_url, notice: 'Image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def image_params
      params.require(:image).permit(:name, :tags, :photo, :price)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    client = JWPlayer::API::Client.new
    url = client.signed_url('videos/list')
    @videos = HTTParty.get(url)["videos"]
    @images = Image.to_shop(current_user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
  def jwplayer_video_tag video_id
    src = "//content.jwplatform.com/players/#{video_id}-#{ENV["JWPLAYER_VIDEO_ID"]}.js"
    "<script src=#{src}></script>"
  end
end

app/views/charges/create.html.erb
<%= link_to 'Store', root_path %>
<%= link_to 'My Images', rails_admin_path %>
<h2>Thank you!</h2>
<p>Your paid of <strong><%= number_to_currency(@amount) %></strong> has been received.</p>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <div id="error_explanation">
    <% if flash[:error].present? %>
        <p><%= flash[:error] %></p>
    <% end %>
  </div>
  <article>
    <%= label_tag(:amount, 'Amount:') %>
    <span id="total_amount"><%= @image.price %></span>
  </article>
  <%= hidden_field_tag 'image_id', @image.id %>
  <%= hidden_field_tag 'price', @image.price %>

  <script src="https://checkout.stripe.com/checkout.js"
          class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="Buy the selected image"
          data-amount="<%= @image.price * 100 %>"
          data-locale="auto"></script>
<% end %>

app/views/images/_form.html.erb
<%= form_for(image) do |f| %>
  <% if image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(image.errors.count, "error") %> prohibited this image from being saved:</h2>

      <ul>
      <% image.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :tags %>
    <%= f.text_field :tags %>
  </div>

  <div class="field">
    <%= f.label :photo %>
    <%= f.file_field :photo %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/images/edit.html.erb
<h1>Editing Image</h1>

<%= render 'form', image: @image %>

<%= link_to 'Show', @image %> |
<%= link_to 'Back', images_path %>

app/views/images/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Images</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Tags</th>
      <th>Photo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @images.each do |image| %>
      <tr>
        <td><%= image.name %></td>
        <td><%= image.tags %></td>
        <td><%= image_tag image.photo.url(:square) %><td>
        <td><%= link_to 'Show', image %></td>
        <td><%= link_to 'Edit', edit_image_path(image) %></td>
        <td><%= link_to 'Destroy', image, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Image', new_image_path %>

app/views/images/new.html.erb
<h1>New Image</h1>

<%= render 'form', image: @image %>

<%= link_to 'Back', images_path %>

app/views/images/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @image.name %>
</p>

<p>
  <strong>Tags:</strong>
  <%= @image.tags %>
</p>

<p>
  <strong>Photo:</strong>
  <%= image_tag @image.photo.url(:square) %>
</p>

<%= link_to 'Edit', edit_image_path(@image) %> |
<%= link_to 'Back', images_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsCms</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
  <head></head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<%= link_to 'My Images', rails_admin_path %>

<p id="notice"><%= notice %></p>

<h1>Store</h1>
<table style="width: 100%">
  <thead>
    <tr>
      <th>Video</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @videos.each do |video| %>
      <tr>
        <td><%= jwplayer_video_tag(video["key"]).html_safe %></td>
        <td><%= link_to 'Buy', new_charge_path(video_id: video["key"]) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<table>
  <thead>
    <tr>
      <th>Photo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @images.each do |image| %>
      <tr>
        <td><%= image_tag image.photo.url(:square) %><td>
        <td><%= link_to 'Buy', new_charge_path(image_id: image.id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>